<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ApplicationOverview</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>55aacd87-6e1d-4718-98df-c47ea3694cca</testSuiteGuid>
   <testCaseLink>
      <guid>fd3d09bd-e8f2-4da5-abe4-0af72ec0b6e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify Item Added into the Cart/Verify Item Added into the Cart</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>48e82759-5658-49d9-a88a-81e3785f2cff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Environment/TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>48e82759-5658-49d9-a88a-81e3785f2cff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>environment</value>
         <variableId>562bf452-6352-4ff4-a1c2-529f7d0f1d9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>48e82759-5658-49d9-a88a-81e3785f2cff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2a842eb1-f949-4cfa-ad16-25ac7a6fe48d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>48e82759-5658-49d9-a88a-81e3785f2cff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>19482570-4d84-42b8-8f82-2891ad50cb3a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
